# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiment',
            name='text',
            field=models.TextField(),
        ),
    ]
